# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70dee51aef2da46bc7ee866648c7e43e3c8950bd8a6eb9e58aacd379d550b80e1d2b58347b73a6c46e1bf45dd3212f017bb5fbe9fd89f39ac7235145b0a579c9

test:
  secret_key_base: e4063edcf77fa7869e66613246e63e8244c56276781b4c10879d1eae84f53d1475e1c3e36571889fa158f0138edb56529047a631f92473ec4ed01cf9904c5916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
